### ISSUE TITLE
Integrasi ke Clahub.com

### ISSUE THREAD

**Issue by feryardiant** [codeigniter-id/codeigniter-id.github.io#10]
Saya rasa ini akan sangat diperlukan bagi setiap calon kontributor sebelum submit code mereka baik ke landing page maupun ke repo lain di org ini.

Jadi setiap aturan (terkait teknologi yg dipakai, aturan penulisan, dll) akan dimuat dlm file **contribution.md** dan harus _ditandatangani_ sebelum mereka bikin pull request.

link: https://www.clahub.com

any thought?

**Comment by SunDi3yansyah** [comment]
Please add this CONTRIBUTING root project and page on ph-page CI Indonesia :smile: 
https://github.com/codeigniter-id/codeigniter-id.github.io/blob/master/CONTRIBUTING.md
https://github.com/codeigniter-id/codeigniter-id.github.io/tree/master/app/teams

**Comment by feryardiant** [comment]
:+1:

---

Best :)
Fery Wardiyanto
