### ISSUE TITLE
nbproject folder

### ISSUE THREAD

**Issue by reyhansofian** [codeigniter-id/codeigniter-id.github.io#12]
Apa perlu kita masuk kan folder nbproject ke .gitignore?

**Comment by SunDi3yansyah** [comment]
itu folder dari netbean ya? soalnya yang built pagenya bukan saya, saya baru ngerapiin data nya aja

**Comment by reyhansofian** [comment]
Iya, biasanya punya netbeans. Mungkin lebih baik masuk .gitignore aja kali ya? Soalnya ga semua pke netbeans.

**Comment by SunDi3yansyah** [comment]
:+1: 
Done
