### ISSUE TITLE
teknologi yang di pakai untuk landing page

### ISSUE THREAD

**Issue by puterakahfi** [codeigniter-id/codeigniter-id.github.io#2]
landing page menggunakan bootstrap, angular js

dan halaman di buat static
## kategori

untuk kategori di buat halaman sendiri, misalnya di halaman artikel, ada halaman sendiri untuk menampilkan semua list artikel, ada fitur pencarian untuk memudahkan proses pencarian artikel, tagging, kategori ( artikel berdasarkan jenisnya)
## projects

berisi halaman-halaman list library, plugins, project2x opensource lainnya yang berguna sehingga memudahkan pengunjung dalam problem solving
## powered by codeigniter

halaman ini berisi list web yang di buat menggunakan codeiniter, silahkan jika ada member yang web nya mau di masukkan di sini ( nanti tinggal di tambahkan sendiri)

**Comment by SunDi3yansyah** [comment]
Saya punya usul.
Ini kan jenisnya static, ada generatornya atau tidak?
Misalnya klo dipake-in Jekyll, Middleman, Octopress, etc gimana mas :smile:

**Comment by puterakahfi** [comment]
yup sepenernya mau pake jekyll, atau octopress (lebih prefer ke jekyll karena di support di githubnya), tapi nanti nggak banyak yang contribute, makanya di bikin static pake angular js

**Comment by SunDi3yansyah** [comment]
nggak semua member nanti bisa main-an jekyll gitu ya jadi dikit yang kontribusi.
oke klo gitu mas, bisa di mengerti. :+1:

**Comment by puterakahfi** [comment]
yup, sambil jalan aja, kalo ketemu modul2x angularjs buat static generator bisa juga, di tampung dulu

**Comment by titounnes** [comment]
Setuju dengan angular. Biat lebih membumi.

**Comment by puterakahfi** [comment]
yup, sekarang sudah ada activity di landing pagenya, ane baru tau ada comment baru pas liat landing pagenya :)

**Comment by puterakahfi** [comment]
btw untuk aturan penulisan kodenya angularjs, kita ngikutin aturannya john papa 
bisa di akses di  sini 

https://github.com/johnpapa/angular-styleguide

**Comment by feryardiant** [comment]
+1 untuk static site generator (Jekyll atau Hexo)

**Comment by dikiaap** [comment]
:metal:

**Comment by reyhansofian** [comment]
+1 untuk angular

**Comment by dikiaap** [comment]
pake jekyll / octopress wae? :octocat:

**Comment by SunDi3yansyah** [comment]
gimana aja deh enak nya biar enak :smile:
