### ISSUE TITLE
Database artikel

### ISSUE THREAD

**Issue by yogasukma** [codeigniter-id/codeigniter-id.github.io#4]
Untuk artikel (dan lainnya) daripada ngetik hardcode ke template modal artikel nya, gimana kalau dibuatin di file json? jadi ntar tinggal edit artikel.json lalu kemudian di tarik untuk ditampilin di modal window nya kumpulan artikel?

**Comment by puterakahfi** [comment]
yup rencananya di buat file json, sementara kita bikin struktur aplikasinya dulu

**Comment by zhiephie** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/5674973/10396453/b4e2ba0e-6ecc-11e5-9218-38b424ead350.png)

Testing :palm_tree:

**Comment by zhiephie** [comment]
boleh commit g nih om @puterakahfi

**Comment by puterakahfi** [comment]
mantab, pake apa om @zhiephie  ? json ato loki ?
commit aja :+1:

**Comment by zhiephie** [comment]
json om. nanti tampilan tinggal disesuaikan ya. yg lain jg biar ikutan :dancer:

**Comment by puterakahfi** [comment]
yup, ane lagi ngurusin tampilannya, untuk animasinya sudah bisa jalan, tinggal bikin tampilan untuk child pages nya.

**Comment by zhiephie** [comment]
:ok:

**Comment by yogasukma** [comment]
wah saya gak liat, saya barusan pull request module artikel :smile:

**Comment by zhiephie** [comment]
sorry mas bentrok sama saya tadi

**Comment by yogasukma** [comment]
eh tapi jadi gak works artikel nya, baik punya saya maupun punya mu, artikel nya masih nge load si popup

**Comment by puterakahfi** [comment]
done, using GET not POST

**Comment by zhiephie** [comment]
POST tadi jalan om, kan di commit ada ane update GET jg..haha

om @ysupr popup mungkin clicknya gambarnya ya? coba title artikel itu dclick

**Comment by puterakahfi** [comment]
kalo di local mungkin jalan pake method POST, kalo di servernya git dapet 403 tadi tak liat ( not allowed access), tapi kurang tau juga

**Comment by yogasukma** [comment]
Ho iya bener, klik di judul artikel nya, mungkin ntar di tambahin di gambarnya juga kali ya, ada hover effect nya soalnya normalnya bakal nge klik gambar :smile:
